server:
  port: 8080
spring:
  application:
    name: spring-boot-quickstart
  datasource:
    druid:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/demo?userSSL=false&useUnicode=true&characterEncoding=utf8&useAffectedRows=true
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat,wall
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: ltx
        login-password: ltx@2021
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

file:
  baseUrl: "http://10.32.139.162:8082/services/rule/api/alertrule"
  Authorization: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjU5MmVjNzQ4LWMzYjAtNDAwNi05NjgwLTM4MGI2ZGQ4ZmQzZiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6ImdhdGV3YXlfYXBwIiwibmJmIjoxNjk1Mzg3Nzg0LCJhenAiOiJnYXRld2F5X2FwcCIsImV4cCI6MTY5NTQwMjE4NCwiaWF0IjoxNjk1Mzg3Nzg0LCJqdGkiOiI0N2Y0ZDU0MC1lYWQ0LTQ1NGQtODk0MS0xZTI5NzgxNGVhZjQifQ.3P2tCwFC2355lZEO9H1P78WEs5kl33Fe1o66N6J9kwzX6zDriGaKxQrkCytuLs7W8idNBlP6b7GKEgWDM6aXUJzaxS7KnLYFxhyM9zsS2g6fQd8ztAIJroS5ts5BVbC5Y-LutxD82_QlViEJtl8464zNXpmEzPICC9FH4s9oQ2gD2CRQ3IktkZa5VT4ntbW2T8U8XUPxNpwgjX4pr9hGTVs6vHMy9asAe9f5AyYRd0vIv4nnf5PESGUwwTTnPWnCe4DjkebLasHBjla8isUHR059VKP7ObClvVJoWb5ccgp5lNFE_aq3mXOq6-pQ_EmzhrPY4t865Ewz5QVUlUz1bw"
  Cookie: "XC-Uaa-Csrf=eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIwYWJiOTliYTljYzg0MDgwYTE0ZGY3YTBmYTdlYWQ2NiIsInVzZXIiOiJhZG1pbiIsInN1YiI6ImFkbWluIn0.h8QhClG3cVjZQ0oOnbj01V0fxDSBWecfv247mTqInWSgjB4oRndMDvdZGqbB_fmeJCvAEynNYW3p-uXuDVNJaQ; xdrijn-TOEKN=Bearer%20eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjU5MmVjNzQ4LWMzYjAtNDAwNi05NjgwLTM4MGI2ZGQ4ZmQzZiJ9.eyJzdWIiOiJhZG1pbiIsImF1ZCI6ImdhdGV3YXlfYXBwIiwibmJmIjoxNjk1Mzg3Nzg0LCJhenAiOiJnYXRld2F5X2FwcCIsImV4cCI6MTY5NTQwMjE4NCwiaWF0IjoxNjk1Mzg3Nzg0LCJqdGkiOiI0N2Y0ZDU0MC1lYWQ0LTQ1NGQtODk0MS0xZTI5NzgxNGVhZjQifQ.3P2tCwFC2355lZEO9H1P78WEs5kl33Fe1o66N6J9kwzX6zDriGaKxQrkCytuLs7W8idNBlP6b7GKEgWDM6aXUJzaxS7KnLYFxhyM9zsS2g6fQd8ztAIJroS5ts5BVbC5Y-LutxD82_QlViEJtl8464zNXpmEzPICC9FH4s9oQ2gD2CRQ3IktkZa5VT4ntbW2T8U8XUPxNpwgjX4pr9hGTVs6vHMy9asAe9f5AyYRd0vIv4nnf5PESGUwwTTnPWnCe4DjkebLasHBjla8isUHR059VKP7ObClvVJoWb5ccgp5lNFE_aq3mXOq6-pQ_EmzhrPY4t865Ewz5QVUlUz1bw"
  excelPath: "C:\\My_Work\\IdeaProjects\\hello_world\\src\\main\\java\\com\\hy\\springbootquickstart\\file\\alarm_rules.xlsx"